### ISSUE TITLE
Push Python 3.6 version to Docker Hub?

### ISSUE THREAD

**Issue by singingwolfboy** [datagovsg/python-node#3]
This Docker image [is on Docker Hub](https://hub.docker.com/r/datagovsg/python-node/), but only with Python 3.5. Can you push the 3.6 version to Docker Hub, as well?

**Comment by chrissng** [comment]
ok there u go: https://hub.docker.com/r/datagovsg/python-node/tags/

**Comment by singingwolfboy** [comment]
Thanks!
